### ISSUE TITLE
ProjectServiceTests Fails

### ISSUE THREAD

**Issue by alexbevi** [gmarland/GhostRunner#1]
https://github.com/gmarland/GhostRunner/blob/master/GhostRunner.Tests/SL/ProjectServiceTests.cs#L73

Test doesn't match `DeleteProject` signature of `public Boolean DeleteProject(String projectId, String packageCacheLocation)`

**Comment by gmarland** [comment]
Thanks for finding this. I will investigate.

**Comment by gmarland** [comment]
Fixed. All tests should now be passing
